# Generated by Django 4.1 on 2022-08-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Blog Post', max_length=100),
            preserve_default=False,
        ),
    ]
